# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20171127_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
