# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
